# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Senior Design' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Senior Design
  pod 'SnapKit', '~> 4.0.0'
  pod 'STPopup','~> 1.8.2'
  pod 'JASON', '~> 3.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'Alamofire', '~> 4.5.0'
  pod 'AlamofireImage', '~> 3.3.0'
  pod 'ChameleonFramework', '~> 2.1.0'
  pod 'ScrollableGraphView'

end
